version: '3'

services:
  remake-docketeer:
    image: ${DESKTOP_PLUGIN_IMAGE}
    container_name: remake-docketeer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - docketeer-prometheus-files:/prometheus
      - docketeer-grafana-files:/grafana
    ports:
      - 3333:3333

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - docketeer-prometheus-data:/prometheus
      - docketeer-prometheus-files:/etc/prometheus
    depends_on:
      - remake-docketeer

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 2999:3000
    volumes:
      - docketeer-grafana-files:/etc/grafana
    environment:
      GF_PATHS_CONFIG: /etc/grafana/grafana.ini
    depends_on:
      - prometheus

  db:
    image: docketeerxii/postgres
    container_name: docketeerdb
    ports:
      - '5432:5432'
    volumes:
      - docketeer-db-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: 'docketeer-db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    depends_on:
      - prometheus
  node-exporter:
    image: docketeerxii/nodeex
    container_name: node-exporter
    ports:
      - '9100:9100'
    volumes:
      #system info for linux machines
      - /proc:/host/proc:ro
      # also for linux
      - /sys:/host/sys:ro
      #root
      - /:/rootfs:ro
    depends_on:
      - db

volumes:
  docketeer-prometheus-data:
  docketeer-prometheus-files:
  docketeer-grafana-files:
  docketeer-db-data:
