version: '3'

services:
  remake-docketeer:
    image: ${DESKTOP_PLUGIN_IMAGE}
    container_name: remake-docketeer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - docketeer-prometheus-files:/prometheus
      - docketeer-grafana-files:/grafana
      - docketeer-postgres-db:/postgres
    ports:
      - 4000:4000

  db:
    image: docketeerxii/postgres
    container_name: docketeerdb
    ports:
      - '5432:5432'
    volumes:
      - docketeer-postgres-db:/postgres
    environment:
      POSTGRES_DB: 'docketeer-db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - '9100:9100'
    command: 
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)
    volumes:
      #system info for linux machines
      - /proc:/host/proc:ro
      # also for linux
      - /sys:/host/sys:ro
      #root
      - /:/rootfs:ro
    depends_on:
      - db

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - docketeer-prometheus-data:/prometheus
      - docketeer-prometheus-files:/etc/prometheus
    depends_on:
      - node-exporter
    labels:
      org_prometheus_starter: 'true'
      org_prometheus_starter_port: '9090'
      org_prometheus_starter_path: '/metrics'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 2999:3000
    volumes:
      - docketeer-grafana-files:/etc/grafana
    environment:
      GF_PATHS_CONFIG: /etc/grafana/grafana.ini
    depends_on:
      - prometheus



volumes:
  docketeer-prometheus-data:
  docketeer-prometheus-files:
  docketeer-grafana-files:
  docketeer-postgres-db:
