services:
  remake-docketeer:
    image: ${DESKTOP_PLUGIN_IMAGE}
    container_name: remake-docketeer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Create volumes which are mapped to /grafana and /prometheus folder in the extension container
      - docketeer-prometheus-files:/prometheus
      - docketeer-grafana-files:/grafana
    ports:
      # Expose port 3333 to the host so that you can see metrics on localhost:3333/metrics
      - 3333:3333

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      # Execute command to create the config file to run prometheus
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      # Create a named volume for the prometheus data
      - docketeer-prometheus-data:/prometheus
      # Share the named volume with the prometheus container
      - docketeer-prometheus-files:/etc/prometheus
    depends_on:
      - remake-docketeer

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      # Expose the ports so we can show them on the frontend UI
      - 2999:3000
    volumes:
      # Share the named volume with the grafana container
      - docketeer-grafana-files:/etc/grafana
    environment:
      GF_PATHS_CONFIG: /etc/grafana/grafana.ini
    depends_on:
     - prometheus

volumes:
  docketeer-prometheus-data:
  docketeer-prometheus-files:
  docketeer-grafana-files:
