apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    user: admin
    database: docketeer
    secureJsonData:
      password: 'admin'
    jsonData:
      tlsAuth: false
      sslmode: 'disable' # disable/require/verify-ca/verify-full